### ISSUE TITLE
does this only work in browsers

### ISSUE THREAD

**Issue by rifkegribenes** [ibleaman/Yiddish-Klal#4]
hi, i installed the keyboard layout according to instructions and it works fine to type in a browser / webform but i can't get it to work in desktop applications (like textedit, excel). i'm using mac os 10.15.7. just wondering if there's something i missed in setup that would make it work in other apps? thanks

**Comment by ibleaman** [comment]
Did you restart your computer after installing the layout? That usually solves this problem.
